package ru.andrew.application.domain

enum class EquipmentType {
    DOMESTIC_REFRIGERATOR,
    COMMERCIAL_EQUIPMENT,
    INDUSTRIAL_EQUIPMENT,
    ICE_GENERATOR,
    FREEZER_CHAMBER,
    REFRIGERATED_SHOWCASE,
    SPLIT_SYSTEM,
    OTHER
}
