package ru.andrew.application.ui.theme

import androidx.compose.ui.graphics.Color

internal val AppBackground = Color(0xFFFAFCFB)
internal val AppOnBackground = Color(0xFF17211F)
internal val AppPrimary = Color(0xFF245F5B)
internal val AppOnPrimary = Color(0xFFFFFFFF)
internal val AppPrimaryContainer = Color(0xFFD3F0EC)
internal val AppOnPrimaryContainer = Color(0xFF06201D)
internal val AppInversePrimary = Color(0xFFA7D8D2)
internal val AppPrimaryFixed = Color(0xFFD3F0EC)
internal val AppPrimaryFixedDim = Color(0xFFA7D8D2)
internal val AppOnPrimaryFixed = Color(0xFF06201D)
internal val AppOnPrimaryFixedVariant = Color(0xFF164541)
internal val AppSecondary = Color(0xFF6BA8A2)
internal val AppOnSecondary = Color(0xFF0E1F1D)
internal val AppSecondaryContainer = Color(0xFFE4F4F1)
internal val AppOnSecondaryContainer = Color(0xFF15211F)
internal val AppSecondaryFixed = Color(0xFFE4F4F1)
internal val AppSecondaryFixedDim = Color(0xFFB8DCD8)
internal val AppOnSecondaryFixed = Color(0xFF0E1F1D)
internal val AppOnSecondaryFixedVariant = Color(0xFF3C5C58)
internal val AppTertiary = Color(0xFF516168)
internal val AppOnTertiary = Color(0xFFFFFFFF)
internal val AppTertiaryContainer = Color(0xFFD9E7EC)
internal val AppOnTertiaryContainer = Color(0xFF101F25)
internal val AppTertiaryFixed = Color(0xFFD9E7EC)
internal val AppTertiaryFixedDim = Color(0xFFB8CCD3)
internal val AppOnTertiaryFixed = Color(0xFF101F25)
internal val AppOnTertiaryFixedVariant = Color(0xFF39494F)
internal val AppError = Color(0xFFBA1A1A)
internal val AppOnError = Color(0xFFFFFFFF)
internal val AppErrorContainer = Color(0xFFFFDAD6)
internal val AppOnErrorContainer = Color(0xFF410002)
internal val AppOnSurface = Color(0xFF17211F)
internal val AppSurfaceVariant = Color(0xFFE6EEEB)
internal val AppOnSurfaceVariant = Color(0xFF3D4D49)
internal val AppInverseSurface = Color(0xFF263331)
internal val AppInverseOnSurface = Color(0xFFEFF8F5)
internal val AppOutline = Color(0xFF6E807C)
internal val AppOutlineVariant = Color(0xFFC5D2CF)
internal val AppScrim = Color(0xFF000000)
internal val AppSurfaceTint = AppPrimary
internal val AppSurfaceContainerLowest = Color(0xFFFFFFFF)
internal val AppSurfaceContainerLow = Color(0xFFF3F8F6)
internal val AppSurfaceContainer = Color(0xFFEDF3F1)
internal val AppSurfaceContainerHigh = Color(0xFFE6EEEB)
internal val AppSurfaceContainerHighest = Color(0xFFDEE8E5)
internal val AppSurfaceDim = Color(0xFFD8E2DF)
internal val AppSurfaceBright = Color(0xFFFAFCFB)
internal val UrgentOrange = Color(0xFFD65A00) // Оранжевый индикатор срочности ("Сегодня") для светлой темы

// Premium Dark Theme Color Tokens (Сине-серая палитра)
internal val DarkAppBackground = Color(0xFF0F172A) // очень темный сине-серый (slate-900)
internal val DarkAppOnBackground = Color(0xFFE2E8F0) // светлый серо-синий текст
internal val DarkAppPrimary = Color(0xFF38BDF8) // яркий голубой акцент (cyan-400)
internal val DarkAppOnPrimary = Color(0xFF082F49) // глубокий темный синий
internal val DarkAppPrimaryContainer = Color(0xFF0369A1) // темно-синий контейнер (sky-700)
internal val DarkAppOnPrimaryContainer = Color(0xFFBAE6FD) // светло-голубой текст контейнера
internal val DarkAppSecondary = Color(0xFF818CF8) // голубо-синий вторичный (sky-400)
internal val DarkAppOnSecondary = Color(0xFF0C4A6E)
internal val DarkAppSecondaryContainer = Color(0xFF1E3A8A) // blue-900
internal val DarkAppOnSecondaryContainer = Color(0xFFDBEAFE)
internal val DarkAppTertiary = Color(0xFF80DEEA) // бирюзово-голубой
internal val DarkAppOnTertiary = Color(0xFF00363A)
internal val DarkAppTertiaryContainer = Color(0xFF004D40)
internal val DarkAppOnTertiaryContainer = Color(0xFFE0F7FA)
internal val DarkAppError = Color(0xFFFFB4AB)
internal val DarkAppOnError = Color(0xFF690005)
internal val DarkAppErrorContainer = Color(0xFF93000A)
internal val DarkAppOnErrorContainer = Color(0xFFFFDAD6)
internal val DarkAppOnSurface = Color(0xFFE0E8E5)
internal val DarkAppSurfaceVariant = Color(0xFF3F4946)
internal val DarkAppOnSurfaceVariant = Color(0xFFBEC9C5)
internal val DarkAppInverseSurface = Color(0xFFE0E8E5)
internal val DarkAppInverseOnSurface = Color(0xFF17211F)
internal val DarkAppOutline = Color(0xFF899390)
internal val DarkAppOutlineVariant = Color(0xFF3F4946)
internal val DarkAppScrim = Color(0xFF000000)
internal val DarkAppSurfaceTint = DarkAppPrimary
internal val DarkAppSurfaceContainerLowest = Color(0xFF020617) // slate-950
internal val DarkAppSurfaceContainerLow = Color(0xFF0F172A) // slate-900
internal val DarkAppSurfaceContainer = Color(0xFF1E293B) // slate-800
internal val DarkAppSurfaceContainerHigh = Color(0xFF334155) // slate-700
internal val DarkAppSurfaceContainerHighest = Color(0xFF475569) // slate-600
internal val DarkAppSurfaceDim = Color(0xFF0F172A)
internal val DarkAppSurfaceBright = Color(0xFF1E293B)
internal val DarkUrgentOrange = Color(0xFFFFB066) // Оранжевый индикатор срочности ("Сегодня") для темной темы

