// Automatically generated by pr_reviewer.py. Do not edit manually.
const evaluationsData = {
  "Этап 0. Каркас проекта": "95/100",
  "Этап 1. Слой данных": "88/100"
};

const latestReview = {
  "stage_name": "Этап 1. Слой данных",
  "score": 88,
  "summary": "Реализован базовый слой данных Room DB, включая сущность `Request`, TypeConverters и DAO методы. Добавлен репозиторий `RequestRepository` для управления бизнес-логикой и состояниями заявок.",
  "bugs_and_issues": [
    {
      "file_path": "app/src/main/java/ru/andrey/applications/data/dao/RequestDao.kt",
      "line_number": 42,
      "severity": "MEDIUM",
      "description": "Метод вставки использует OnConflictStrategy.REPLACE, что может непреднамеренно перезаписывать поля updatedAt или createdAt, сбрасывая их на дефолтные значения при обновлении."
    },
    {
      "file_path": "app/src/main/java/ru/andrey/applications/data/repository/RequestRepository.kt",
      "line_number": 87,
      "severity": "HIGH",
      "description": "Вызовы Room базы данных в RequestRepository выполняются на Dispatchers.Main. Рекомендуется переключить контекст на Dispatchers.IO во избежание фризов основного интерфейса при интенсивных дисковых операциях."
    },
    {
      "file_path": "app/src/main/java/ru/andrey/applications/data/converters/DateConverters.kt",
      "line_number": 15,
      "severity": "LOW",
      "description": "Используется неоптимальный парсер дат. Рекомендуется использовать встроенный ISO-8601 парсер или хранить временные метки как Long (Unix timestamp) для упрощения сортировок в БД."
    }
  ],
  "recommendations": [
    "Используйте Dispatchers.IO для всех операций репозитория с базой данных Room.",
    "Реализуйте миграции базы данных или включите fallbackToDestructiveMigration() во время активной разработки каркаса.",
    "Покройте DAO-методы юнит-тестами для проверки сортировки активного списка и истории заявок."
  ]
};
